name: voicecut_studio
description: Accessible video editor with browser-based media processing.
publish_to: none
version: 2.5.0+11
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: 6.1.5
  permission_handler: 11.4.0
  path_provider: 2.1.5
  share_plus: 10.1.4
  flutter_local_notifications: 18.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
flutter:
  uses-material-design: true
